name: Run API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instala dependências
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: 🧪 Executa os testes de autenticação
        id: autenticacao
        run: |
          newman run ./test/autenticacao_collection.json \
            --env-var base_url=https://animesapi-production-afranio.up.railway.app \
            -r cli,htmlextra \
            --reporter-htmlextra-export=autenticacao-report.html
          # Extrair o token de autenticação da resposta e definir como variável de ambiente
          echo "AUTH_TOKEN=$(newman run ./test/autenticacao_collection.json --env-var base_url=https://animesapi-production-afranio.up.railway.app | grep -oP '(?<=token":")[^"]+')" >> $GITHUB_ENV

      - name: 🧪 Executa os testes de funcionalidade
        run: |
          newman run ./test/funcionalidade_collection.json \
            --env-var base_url=https://animesapi-production-afranio.up.railway.app \
            --env-var auth_token=${{ env.AUTH_TOKEN }} \
            -r cli,htmlextra \
            --reporter-htmlextra-export=funcionalidade-report.html

      - name: 📤 Publica o relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Newman
          path: newman-report.html
